//-------------------------------------------------------------
//  テンプレートスクリプト (スクリプトの処理内容を記述する。)
//  これを参考にスクリプトを作ってください。
//
//  code by m_yamada (作成者) を記述する。
//-------------------------------------------------------------

using UnityEngine;
using System.Collections;

public class TemplateScript : MonoBehaviour 
{

    /// <summary>
    /// Editorのみ変更可能にする。 
    /// </summary>
    [SerializeField]
    int value = 0;

    [SerializeField]
    GameObject attackObject;


    /// <summary>
    /// スクリプトのインスタンスがロードされたときに呼び出されます
    /// </summary>
    void Awake()
    {
    }

    /// <summary>   
    /// Update メソッドが最初に呼び出される前のフレームで呼び出されます
    /// </summary>
    void Start()
    {
    }

    /// <summary>
    /// 毎フレーム呼ばれる。
    /// </summary>
    void Update()
    {

    }

    /// <summary>
    /// Behaviour が有効の場合、LateUpdate は毎フレーム呼びだされます
    /// </summary>
    void LateUpdate()
    {

    }

    /// <summary>
    /// MonoBehaviour が有効の場合、この関数は毎回、固定フレームレートで呼び出されます。
    /// </summary>
    void FixedUpdate()
    {

    }

}
